"""Set default updated_at for chores

Revision ID: 036b8eb62e92
Revises: f0169f2dcca7
Create Date: 2025-04-05 17:58:00.664687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036b8eb62e92'
down_revision: Union[str, None] = 'f0169f2dcca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chores', 'updated_at', server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chores', 'updated_at', server_default=None)
    pass
    # ### end Alembic commands ###
