"""Add admin_id to families

Revision ID: 6494842c9b77
Revises: 036b8eb62e92
Create Date: 2025-05-14 18:07:26.529851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6494842c9b77'
down_revision: Union[str, None] = '036b8eb62e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'families', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_column('families', 'admin_id')
    # ### end Alembic commands ###
