"""Remove admin_id foreign key constraint

Revision ID: aed02c6b9e89
Revises: c82d59d5cbd2
Create Date: 2025-05-16 13:25:04.277204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed02c6b9e89'
down_revision: Union[str, None] = 'c82d59d5cbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('families_admin_id_fkey', 'families', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('families_admin_id_fkey', 'families', 'users', ['admin_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
