"""Make admin_id foreign key deferrable

Revision ID: c82d59d5cbd2
Revises: <revision_id>
Create Date: 2025-05-16 12:57:36.128215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82d59d5cbd2'
down_revision: Union[str, None] = '<revision_id>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('families_admin_id_fkey', 'families', type_='foreignkey')
    op.create_foreign_key(None, 'families', 'users', ['admin_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.create_foreign_key('families_admin_id_fkey', 'families', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
